spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tasks_db
    username: root
    password: # If you have a password, add it here, otherwise leave it empty
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
